version: '3.8'

services:
  web:
    build:
      context: "./inonexus_backend/Innonexus"
    volumes:
      - "./inonexus_backend/Innonexus:/home/straighthup/code"
      - staticfiles:/home/straighthup/code/static
      - "./inonexus_backend/Innonexus/media:/home/straighthup/code/media/"
    ports:
      - "8000:8000"
    environment:
      - DEBUG="false"

  frontend:
    build:
      context: "./innoProject"
    volumes:
      - front:/app/build/

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:8080" 
      - "443:443"
    volumes:
      - front:/var/www/straighthup/frontend
      - staticfiles:/var/www/straighthup/static
      - mediafiles:/var/www/straighthup/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Update these lines to point to your .pem files
      -./Innonexus/ssl/server.straighthup.com.pem:/etc/ssl/certs/server.straighthup.com.pem:ro
      -./Innonexus/ssl/server.straighthup.private.pem:/etc/ssl/private/server.straighthup.private.pem:ro
    depends_on:
      - frontend
      - web

volumes:
  staticfiles:
  mediafiles:
  front:
