version: '3.8'

services:
  web:
    build:
      context: "./inonexus_backend/Innonexus"
    command: gunicorn Innonexus.wsgi --bind 0.0.0.0:8000 --workers 3
    volumes:
      - "./inonexus_backend/Innonexus:/home/straighthup/code"
      - staticfiles:/home/straighthup/code/static
      - "./inonexus_backend/Innonexus/media:/home/straighthup/code/media/"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: "./innoProject"
    ports:
      - "80:80"
    volumes:
      - front:/app/build/
      

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - front:/var/www/straighthup/frontend
      - staticfiles:/var/www/straighthup/static
      - ./Innonexus/ssl/server.straighthup.com.crt:/etc/ssl/certs/server.straighthup.com.crt:ro
      - ./Innonexus/ssl/server.straighthup.com.key:/etc/ssl/private/server.straighthup.com.key:ro
    depends_on:
      - frontend
      - web

volumes:
  staticfiles:
  front:
