services:
  web:
    build:
      context: "./inonexus_backend/Innonexus"
    command: gunicorn Innonexus.wsgi --bind 0.0.0.0:8000 --workers 3
    volumes:
      - "./inonexus_backend/Innonexus:/home/straighthup/code"
      - staticfiles:/home/straighthup/code/staticfiles
      - "./inonexus_backend/Innonexus/media:/home/straighthup/code/media/"
    ports:
      - "8000:8000"

  frontend:
    build: "./innoProject"
    volumes:
      - front:/app/build/

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - front:/var/www/straighthup/frontend
      - staticfiles:/var/www/straighthup/static
      - mediafiles:/var/www/straighthup/code/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/private:/etc/ssl/private:ro
    depends_on:
      - frontend
      - web

volumes:
  staticfiles:
  mediafiles:
  front:
