version: "3.9"

services:
  web:
    build:
      context: "./inonexus_backend/Innonexus"
    command: gunicorn Innonexus.wsgi --bind 0.0.0.0:8000 --workers 3
    volumes:
      - "./inonexus_backend/Innonexus:/home/straighthup/code"
      - staticfiles:/home/straighthup/code/staticfiles
      - ./inonexus_backend/Innonexus/media:/home/straighthup/code/media
    # Remove the ports section
    # ports:
    #   - "8000:8000"

  frontend:
    build:
      context: "./innoProject"
    volumes:
      - front:/app/build/

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"   # Nginx listens on 8080 on the host
      - "8443:443"  # SSL traffic, change as needed
    volumes:
      - front:/var/www/straighthup/frontend
      - staticfiles:/var/www/straighthup/statics
      - mediafiles:/var/www/straighthup/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - web

volumes:
  staticfiles:
  mediafiles:
  front:
